apiVersion: v1
kind: Pod
metadata:
  name: app-secret-env
spec:
  restartPolicy: Never
  containers:
    - name: dokicontainer
      image: redis
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: dokisecret1
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dokisecret1
              key: password