apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: app-cronjob
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curl
              image: bash
              command: ["curl", "localhost:8080"]
          restartPolicy: OnFailure