apiVersion: v1
kind: Pod
metadata:
  name: app-readiness
spec:
  containers:
    - name: app
      image: gcr.io/doki-417600/demo:v1.0.0
      ports:
        - containerPort: 8080
          name: http
      livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 180
        periodSeconds: 10
        failureThreshold: 5
      readinessProbe:
        httpGet:
          path: /ready
          port: 8080
        initialDelaySeconds: 0
        periodSeconds: 2
        failureThreshold: 3
        successThreshold: 1