apiVersion: v1
kind: Pod
metadata:
  name: app-resource
spec:
  containers:
    - name: app
      image: gcr.io/doki-417600/demo:v1.0.0
      ports:
        - containerPort: 8080
          name: http
      livenessProbe:
        httpGet:
          path: /healthy
          port: 8088
        initialDelaySeconds: 5
        timeoutSeconds: 180
        periodSeconds: 600
        failureThreshold: 5
      readinessProbe:
        httpGet:
          path: /ready
          port: 8080
        initialDelaySeconds: 0
        periodSeconds: 120
        failureThreshold: 3
        successThreshold: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 100m
          memory: 256Mi