apiVersion: v1
kind: Pod
metadata:
  name: app-volume
spec:
  containers:
    - name: app
      image: gcr.io/doki-417600/demo:v1.0.0
      ports:
        - containerPort: 8080
          name: http
      livenessProbe:
        httpGet:
          path: /healthy
          port: 8088
        initialDelaySeconds: 5
        timeoutSeconds: 180
        periodSeconds: 600
        failureThreshold: 5
      readinessProbe:
        httpGet:
          path: /ready
          port: 8080
        periodSeconds: 120
        initialDelaySeconds: 0
        failureThreshold: 3
        successThreshold: 1
  volumes:
    - name: data
      hostPath:
        path: /var/lib/app
  volumeMounts:
    - mountPath: /data
      name: data